### ISSUE TITLE
Portfolio

### ISSUE THREAD

**Issue by dpasionek** [PaperTrader/PaperTrader#2]
Need to integrate the portfolio class into the views/models.

# What needs to be done
- Creation of the portfolio model (check out models.py to see how it's done)
- Creation of a portfolio view
- Creation of portfolio view template
- Purchasing/Selling/Updating information on portfolio page

**Comment by pkelley** [comment]
Do you mean creation or implementation b/c the Portfolio model looks implemented in models.py?

**Comment by dpasionek** [comment]
I think I was just trying things out. I'm not sure that's what we want to stick with?

That design is open to your creative freedom!


![](https://media.giphy.com/media/PPYimW5T73L6o/giphy.gif)
